# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hi', 'hiSayer']

# Cell
def say_hi(to):
    '''say hi to person 'to' '''
    return f"hi {to}"

# Cell
class hiSayer:
    "Dumb class to spam hi"
    def __init__(self, to):
        self.to = to

    def say(self):
        "Calls function say hi"
        return say_hi(self.to)